package com.example.examen_menu_sqlite_android_app;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import android.content.Intent;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

public class SignUp extends BaseActivity {
    boolean isLogIn;
    private EditText nam;
    private EditText mail;
    private EditText pass;
    private Button registerBtn;
    private TextView sing;
    private int id ;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sign_up);

        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        Intent intent = getIntent();
        isLogIn = intent.getBooleanExtra("isLogIn", false);

        mail = findViewById(R.id.mail);
        nam = findViewById(R.id.name);
        sing = findViewById(R.id.sing);
        pass = findViewById(R.id.password);
        registerBtn = findViewById(R.id.inscriptBtn);
        id=getIntent().getIntExtra("id",-1);
        if (id!=-1){
            registerBtn.setText("Modifier");
            sing.setText("Modifier");
            nam.setText(getIntent().getStringExtra("nom"));
            mail.setText(getIntent().getStringExtra("email"));
            pass.setText(getIntent().getStringExtra("password"));
        }
        registerBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String email = mail.getText().toString().trim();
                String name = nam.getText().toString().trim();
                String password = pass.getText().toString().trim();
                long Id = register(name, email, password);
                if (Id != -1) {
                    if (id==-1) {
                        Toast.makeText(SignUp.this, "DONE!!", Toast.LENGTH_LONG).show();
                        Intent intent = new Intent(SignUp.this, Connect.class);
                        intent.putExtra("isLogIn", true);
                        startActivity(intent);
                    }else{
                        Toast.makeText(SignUp.this, "Modifié !!", Toast.LENGTH_LONG).show();
                        Intent intent = new Intent(SignUp.this, AffichageActivity.class);
                        startActivity(intent);
                    }
                } else {
                    Toast.makeText(SignUp.this, "This email is already registered!!", Toast.LENGTH_SHORT).show();
                    startActivity(new Intent(SignUp.this, Login.class));


                }
            }
        });
    }


    private int register(String name, String email, String password) {
        DataBaseHelper dbHelper = new DataBaseHelper(this);
        Client client = new Client(
                0, // id will be generated by db
                name, email, password);
        if (id==-1) {
            return (int) dbHelper.ajouterClient(client);
        }else{
            client.id=id;
            return dbHelper.modifierClient(client);
        }

    }



@Override
    public void updateMenu(Menu menu) {
        MenuItem login = menu.findItem(R.id.Login);
        MenuItem logout = menu.findItem(R.id.Logout);
        MenuItem singup = menu.findItem(R.id.singUp);
        login.setVisible(isLogIn);
        singup.setVisible(!isLogIn);
        logout.setVisible(!isLogIn);
    }
}